### ISSUE TITLE
300版本消息页多次刷新崩溃

### ISSUE THREAD

**Issue by Kostamn** [bggRGjQaUbCoE/c001apk#24]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at o000Oo.o000.OooOO0o(SourceFile:28)
	at o0OoOo0.o00O0000.OooOOO0(SourceFile:1)
	at o0OoOo0.o00O0000.OooO00o(SourceFile:146)
	at o0OoOo0.OooOo00.OooOO0o(SourceFile:26)
	at o0OoOo0.o00O0000.OooOOO0(SourceFile:1)
	at o0OoOo0.o00O0000.OooO00o(SourceFile:146)
	at o0OoOo0.o00O0OO.OooOO0O(SourceFile:1226)
	at o0OoOo0.o0000OO0.OooO0O0(SourceFile:63)
	at androidx.recyclerview.widget.LinearLayoutManager.o0000Oo(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.o0000(SourceFile:49)
	at androidx.recyclerview.widget.LinearLayoutManager.Oooooo(SourceFile:819)
	at androidx.recyclerview.widget.RecyclerView.OooOo0(SourceFile:74)
	at androidx.recyclerview.widget.RecyclerView.OooOOoo(SourceFile:72)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:8)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SourceFile:59)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at o000o0o0.o0OO00O.OooOo(SourceFile:144)
	at o000o0o0.oo0o0Oo.OooOO0o(SourceFile:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:41)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at androidx.recyclerview.widget.OooO00o.OoooO00(SourceFile:33)
	at androidx.recyclerview.widget.LinearLayoutManager.o0000Oo(SourceFile:251)
	at androidx.recyclerview.widget.LinearLayoutManager.o0000(SourceFile:49)
	at androidx.recyclerview.widget.LinearLayoutManager.Oooooo(SourceFile:819)
	at androidx.recyclerview.widget.RecyclerView.OooOo0(SourceFile:74)
	at androidx.recyclerview.widget.RecyclerView.OooOOoo(SourceFile:72)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:8)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at androidx.viewpager2.widget.ViewPager2.onLayout(SourceFile:61)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.OooOOo(SourceFile:392)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:47)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:870)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4134)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3510)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2476)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9331)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1390)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1398)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1040)
	at android.view.Choreographer.doFrame(Choreographer.java:954)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1370)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by bggRGjQaUbCoE** [comment]
fixed
